---
title: "STATS 295 Final Project"
format: pdf
editor: source
---
# Confounder

```{r}
set.seed(1234)

sims <- 1000  # Number of simulations
n <- 1000     # Number of observations

# True ATE
ATE <- 0.6

# Direct Method (DM) results
D.M1 <- numeric(sims)
D.M2 <- numeric(sims)


# Simulate data and compute estimates for each method
for (j in 1:sims) {
  Z1 <- rnorm(n,0,1)

  eps_1 <- runif(n,0,1)

  X <- 0.1*Z1^2 + eps_1

  A <- as.integer(X>0.6)

  eps_2 <- rnorm(n,0,1)

  Y <- 0.5*X + A*X + 0.5*Z1 + eps_2

  # Model 1
  fit1 <- lm(Y ~ A + X + A:X)  # Fit the linear model
  
  # Model 2
  
  fit2 <- lm(Y ~ A + X + Z1 + A:X)

  # Extract coefficients from the model
  coef1 <- summary(fit1)$coefficients
  coef2 <- summary(fit2)$coefficients

  
  # Compute potential outcomes for A = 1 and A = 0
  con_mean1.1 <- coef1[1, 1] + coef1[2, 1] + (coef1[3, 1] + coef1[4, 1]) * X  # E[Y | A = 1]
  con_mean0.1 <- coef1[1, 1] + coef1[3, 1] * X  # E[Y | A = 0]
  
  con_mean1.2 <- coef2[1, 1] + coef2[2, 1] + (coef2[3, 1] + coef2[5, 1]) * X + coef2[4,1] * Z1 # E[Y | A = 1]
  con_mean0.2 <- coef2[1, 1] + coef2[3, 1] * X + coef2[4,1] * Z1  # E[Y | A = 0]
  

  
  # Compute ATE for this simulation using the Direct Method
  D.M1[j] <- mean(con_mean1.1) - mean(con_mean0.1)  # ATE using Direct Method
  D.M2[j] <- mean(con_mean1.2) - mean(con_mean0.2)

}

# Bias calculations
D.M_bias1 <- ATE - mean(D.M1)  # Bias for Direct Method
D.M_bias2 <- ATE - mean(D.M2)


D.M_bias <- c(D.M_bias1, D.M_bias2)

# Variance calculations
D.M_var1 <- var(D.M1)  # Variance for Direct Method
D.M_var2 <- var(D.M2)


D.M_var <- c(D.M_var1, D.M_var2)

# Results summary for Direct Method only
results <- data.frame(
  Bias = D.M_bias,
  Variance = D.M_var
)

# Print the results
print(results)
```


# Mediator


```{r}
set.seed(1234)

sims <- 1000  # Number of simulations
n <- 1000     # Number of observations

# True ATE
ATE <- 0.6

# Direct Method (DM) results
D.M1 <- numeric(sims)
D.M2 <- numeric(sims)

# Simulate data and compute estimates for each method
for (j in 1:sims) {

  X <- 0.1*rchisq(n,1) + 0.5

  eps_1 <- runif(n,-1,0)

  Z2 <- sqrt(X) + eps_1

  A <- as.integer(X>0.6)

  eps_2 <- rnorm(n,0,1)

  Y <- 0.5*X + A*X + 0.5*Z2 + eps_2

  # Model 1
  fit1 <- lm(Y ~ A + X + A:X)  # Fit the linear model
  
  # Model 2
  
  fit2 <- lm(Y ~ A + X + Z1 + A:X)

  # Extract coefficients from the model
  coef1 <- summary(fit1)$coefficients
  coef2 <- summary(fit2)$coefficients

  
  # Compute potential outcomes for A = 1 and A = 0
  con_mean1.1 <- coef1[1, 1] + coef1[2, 1] + (coef1[3, 1] + coef1[4, 1]) * X  # E[Y | A = 1]
  con_mean0.1 <- coef1[1, 1] + coef1[3, 1] * X  # E[Y | A = 0]
  
  con_mean1.2 <- coef2[1, 1] + coef2[2, 1] + (coef2[3, 1] + coef2[5, 1]) * X + coef2[4,1] * Z1 # E[Y | A = 1]
  con_mean0.2 <- coef2[1, 1] + coef2[3, 1] * X + coef2[4,1] * Z1  # E[Y | A = 0]
  

  
  # Compute ATE for this simulation using the Direct Method
  D.M1[j] <- mean(con_mean1.1) - mean(con_mean0.1)  # ATE using Direct Method
  D.M2[j] <- mean(con_mean1.2) - mean(con_mean0.2)

}

# Bias calculations
D.M_bias1 <- ATE - mean(D.M1)  # Bias for Direct Method
D.M_bias2 <- ATE - mean(D.M2)

D.M_bias <- c(D.M_bias1, D.M_bias2)

# Variance calculations
D.M_var1 <- var(D.M1)  # Variance for Direct Method
D.M_var2 <- var(D.M2)


D.M_var <- c(D.M_var1, D.M_var2)

# Results summary for Direct Method only
results <- data.frame(
  Bias = D.M_bias,
  Variance = D.M_var
)

# Print the results
print(results)
```


# Precision


```{r}
set.seed(1234)

sims <- 1000  # Number of simulations
n <- 1000     # Number of observations

# True ATE
ATE <- 0.6

# Direct Method (DM) results
D.M1 <- numeric(sims)
D.M2 <- numeric(sims)

# Simulate data and compute estimates for each method
for (j in 1:sims) {

  X <- 0.1*rchisq(n,1) + 0.5

  Z3 <- rnorm(n)

  A <- as.integer(X>0.6)

  eps_2 <- rnorm(n,0,1)

  Y <- 0.5*X + A*X + 0.5*Z3 + eps_2

  # Model 1
  fit1 <- lm(Y ~ A + X + A:X)  # Fit the linear model
  
  # Model 2
  
  fit2 <- lm(Y ~ A + X + Z1 + A:X)

  # Extract coefficients from the model
  coef1 <- summary(fit1)$coefficients
  coef2 <- summary(fit2)$coefficients

  
  # Compute potential outcomes for A = 1 and A = 0
  con_mean1.1 <- coef1[1, 1] + coef1[2, 1] + (coef1[3, 1] + coef1[4, 1]) * X  # E[Y | A = 1]
  con_mean0.1 <- coef1[1, 1] + coef1[3, 1] * X  # E[Y | A = 0]
  
  con_mean1.2 <- coef2[1, 1] + coef2[2, 1] + (coef2[3, 1] + coef2[5, 1]) * X + coef2[4,1] * Z1 # E[Y | A = 1]
  con_mean0.2 <- coef2[1, 1] + coef2[3, 1] * X + coef2[4,1] * Z1  # E[Y | A = 0]
  

  
  # Compute ATE for this simulation using the Direct Method
  D.M1[j] <- mean(con_mean1.1) - mean(con_mean0.1)  # ATE using Direct Method
  D.M2[j] <- mean(con_mean1.2) - mean(con_mean0.2)

}

# Bias calculations
D.M_bias1 <- ATE - mean(D.M1)  # Bias for Direct Method
D.M_bias2 <- ATE - mean(D.M2)

D.M_bias <- c(D.M_bias1, D.M_bias2)

# Variance calculations
D.M_var1 <- var(D.M1)  # Variance for Direct Method
D.M_var2 <- var(D.M2)


D.M_var <- c(D.M_var1, D.M_var2)

# Results summary for Direct Method only
results <- data.frame(
  Bias = D.M_bias,
  Variance = D.M_var
)

# Print the results
print(results)
```


# Nuisance


```{r}
set.seed(1234)

sims <- 1000  # Number of simulations
n <- 1000     # Number of observations

# True ATE
ATE <- 0.6

# Direct Method (DM) results
D.M1 <- numeric(sims)
D.M2 <- numeric(sims)

# Simulate data and compute estimates for each method
for (j in 1:sims) {

  Z4 <- rnorm(n,0,1)

  eps_1 <- runif(n,0,1)

  X <- 0.1*Z4^2 + eps_1

  A <- as.integer(X>0.6)

  eps_2 <- rnorm(n,0,1)

  Y <- 0.5*X + A*X + 0.5*sqrt(X) + eps_2

  # Model 1
  fit1 <- lm(Y ~ A + X + A:X)  # Fit the linear model
  
  # Model 2
  
  fit2 <- lm(Y ~ A + X + Z1 + A:X)

  # Extract coefficients from the model
  coef1 <- summary(fit1)$coefficients
  coef2 <- summary(fit2)$coefficients

  
  # Compute potential outcomes for A = 1 and A = 0
  con_mean1.1 <- coef1[1, 1] + coef1[2, 1] + (coef1[3, 1] + coef1[4, 1]) * X  # E[Y | A = 1]
  con_mean0.1 <- coef1[1, 1] + coef1[3, 1] * X  # E[Y | A = 0]
  
  con_mean1.2 <- coef2[1, 1] + coef2[2, 1] + (coef2[3, 1] + coef2[5, 1]) * X + coef2[4,1] * Z1 # E[Y | A = 1]
  con_mean0.2 <- coef2[1, 1] + coef2[3, 1] * X + coef2[4,1] * Z1  # E[Y | A = 0]
  

  
  # Compute ATE for this simulation using the Direct Method
  D.M1[j] <- mean(con_mean1.1) - mean(con_mean0.1)  # ATE using Direct Method
  D.M2[j] <- mean(con_mean1.2) - mean(con_mean0.2)

}

# Bias calculations
D.M_bias1 <- ATE - mean(D.M1)  # Bias for Direct Method
D.M_bias2 <- ATE - mean(D.M2)

D.M_bias <- c(D.M_bias1, D.M_bias2)

# Variance calculations
D.M_var1 <- var(D.M1)  # Variance for Direct Method
D.M_var2 <- var(D.M2)


D.M_var <- c(D.M_var1, D.M_var2)

# Results summary for Direct Method only
results <- data.frame(
  Bias = D.M_bias,
  Variance = D.M_var
)

# Print the results
print(results)
```
